DROP DATABASE IF EXISTS myapp;

CREATE DATABASE myapp;
USE myapp;

CREATE TABLE LISTS (
    ID INTEGER AUTO_INCREMENT,
    VALUE TEXT,
    PRIMARY KEY(ID)
); 

CREATE TABLE LISTS1 (
    ID INTEGER AUTO_INCREMENT,
    VALUE TEXT,
    PRIMARY KEY(ID)
); 


CREATE TABLE LISTS2 (
    ID INTEGER AUTO_INCREMENT,
    VALUE TEXT,
    PRIMARY KEY(ID)
); 

CREATE TABLE LISTS3 (
    ID INTEGER AUTO_INCREMENT,
    VALUE TEXT,
    PRIMARY KEY(ID)
); 

CREATE TABLE LISTS4 (
    ID INTEGER AUTO_INCREMENT,
    VALUE TEXT,
    PRIMARY KEY(ID)
); 